### ISSUE TITLE
No Text Displayed when using iOS 9

### ISSUE THREAD

**Issue by dvasjuta** [LaunchKey/launchkey-ios-whitelabel-example#2]
When using iOS 9 (simulator or actual device), the labels are missing.

[simulator screen shot 23 oct 2015 12 05 35 pm](https://cloud.githubusercontent.com/assets/9065513/10682219/67a6c6f6-797e-11e5-876b-fbb86a85830f.png)

**Comment by degan** [comment]
Hi David, thanks for the ticket. We have a fix for this and will be pushing an update soon!

**Comment by degan** [comment]
We just pushed the fix to master, please let us know if you have any additional issues.

**Comment by dvasjuta** [comment]
Can mark is fixed now :)
